---
- name: "Deploy OT lab"
  hosts: localhost
  gather_facts: true
  become: true

  vars_files:
    - "vars/networks.yml"
    - "vars/vms.yml"

  tasks:
    - name: "Destroy existing VMs if present"
      community.libvirt.virt:
        name: "{{ item.name }}"
        state: destroyed
        uri: "{{ libvirt_uri }}"
      loop: "{{ vms }}"
      ignore_errors: true
      when: force_redeploy | default(false)

    - name: "Undefine existing VMs if present"
      community.libvirt.virt:
        name: "{{ item.name }}"
        command: undefine
        uri: "{{ libvirt_uri }}"
      loop: "{{ vms }}"
      ignore_errors: true
      when: force_redeploy | default(false)

    - name: "Destroy existing networks if present"
      community.libvirt.virt_net:
        name: "{{ item.name }}"
        state: inactive
        uri: "{{ libvirt_uri }}"
      loop: "{{ networks }}"
      ignore_errors: true
      when: force_redeploy | default(false)

    - name: "Undefine existing networks if present"
      community.libvirt.virt_net:
        name: "{{ item.name }}"
        command: undefine
        uri: "{{ libvirt_uri }}"
      loop: "{{ networks }}"
      ignore_errors: true
      when: force_redeploy | default(false)

  roles:
    - role: network
    - role: vm
