---
firewall_enable_ufw: true

firewall_nft_input_policy: "drop"
firewall_nft_forward_policy: "drop"
firewall_nft_output_policy: "accept"

firewall_ufw_default_input: "deny"
firewall_ufw_default_output: "allow"
firewall_ufw_default_forward: "deny"

firewall_allowed_tcp_ports:
    - 22

firewall_allowed_udp_ports: []

firewall_allowed_forward_rules: []
