---
- name: "Restart CALDERA stack"
  ansible.builtin.command: docker compose up -d
  args:
    chdir: "{{ caldera_dir }}"

roles/caldera/templates/caldera.env.j2 :

CALDERA_NAME={{ caldera_name }}
CALDERA_TIMEZONE={{ caldera_timezone }}
CALDERA_PORT={{ caldera_port }}
