---
- name: "Ensure temporary network directory exists"
  ansible.builtin.file:
      path: "/tmp/ot-lab-networks"
      state: directory
      mode: "0755"

- name: "Render network XML files"
  ansible.builtin.template:
      src: "networks.xml.j2"
      dest: "/tmp/ot-lab-networks/{{ item.name }}.xml"
      mode: "0644"
  loop: "{{ networks }}"

- name: "Define libvirt networks"
  community.libvirt.virt_net:
      command: define
      name: "{{ item.name }}"
      xml: "{{ lookup('file', '/tmp/ot-lab-networks/' ~ item.name ~ '.xml') }}"
      uri: "{{ libvirt_uri }}"
  loop: "{{ networks }}"

- name: "Autostart libvirt networks"
  community.libvirt.virt_net:
      command: autostart
      name: "{{ item.name }}"
      uri: "{{ libvirt_uri }}"
  loop: "{{ networks }}"

- name: "Start libvirt networks"
  community.libvirt.virt_net:
      command: create
      name: "{{ item.name }}"
      uri: "{{ libvirt_uri }}"
  loop: "{{ networks }}"
