---
- name: "Install firewall packages"
  ansible.builtin.apt:
      name:
          - nftables
          - ufw
      state: present
      update_cache: true

- name: "Deploy nftables config"
  ansible.builtin.template:
      src: "nftables.conf.j2"
      dest: "/etc/nftables.conf"
      owner: "root"
      group: "root"
      mode: "0644"
  notify: "Restart nftables"

- name: "Deploy ufw config"
  ansible.builtin.template:
      src: "ufw.conf.j2"
      dest: "/etc/ufw/ufw.conf"
      owner: "root"
      group: "root"
      mode: "0644"

- name: "Enable nftables service"
  ansible.builtin.systemd:
      name: "nftables"
      enabled: true
      state: started

- name: "Enable ufw"
  ansible.builtin.command: ufw --force enable
  changed_when: false
  when: firewall_enable_ufw
