vm_user: "debian"
vm_password: "P@ssw0rd"
vm_password_hash: "$6$VZMHI3IXU/cHNbc6$jhkOYHB1p/MnX3HWHfR3HwaNvjsajvt/diBWfDyFWuP1kbBwdQN/CGse6ykWu6fOh1lUuTv3exDYrXXA7P6Ti/"
vm_become_password_hash: "$6$VZMHI3IXU/cHNbc6$jhkOYHB1p/MnX3HWHfR3HwaNvjsajvt/diBWfDyFWuP1kbBwdQN/CGse6ykWu6fOh1lUuTv3exDYrXXA7P6Ti/"

siem_admin_user: "siem"
siem_admin_password: "$6$VZMHI3IXU/cHNbc6$jhkOYHB1p/MnX3HWHfR3HwaNvjsajvt/diBWfDyFWuP1kbBwdQN/CGse6ykWu6fOh1lUuTv3exDYrXXA7P6Ti/"
