---
- name: "Render CALDERA environment file"
  ansible.builtin.template:
    src: "caldera.env.j2"
    dest: "{{ caldera_dir }}/.env"
    owner: "{{ caldera_user }}"
    group: "{{ caldera_group }}"
    mode: "0644"
  notify: "Restart CALDERA stack"

- name: "Render CALDERA docker compose file"
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ caldera_dir }}/docker-compose.yml"
    owner: "{{ caldera_user }}"
    group: "{{ caldera_group }}"
    mode: "0644"
  notify: "Restart CALDERA stack"

- name: "Deploy custom CALDERA local configuration"
  ansible.builtin.copy:
    src: "conf/local.yml"
    dest: "{{ caldera_config_dir }}/local.yml"
    owner: "{{ caldera_user }}"
    group: "{{ caldera_group }}"
    mode: "0644"
  notify: "Restart CALDERA stack"

- name: "Deploy persistent CALDERA data store"
  ansible.builtin.copy:
    src: "data/"
    dest: "{{ caldera_data_dir }}/"
    owner: "{{ caldera_user }}"
    group: "{{ caldera_group }}"
    mode: "0644"

- name: "Manage CALDERA Docker compose stack"
  community.docker.docker_compose_v2:
    project_src: "{{ caldera_dir }}"
    state: present
    build: always
  when: caldera_docker_enabled | default(true)

